[package]
name = "planning-client"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo = { version = "0.11.0", features = ["timers", "futures"] }
chrono = { version = "0.4.31", features = ["serde"] }
yew = { version = "0.21.0", features = ["csr"] }
yew-hooks = "0.3.0"
