[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.5"
actix-web = "4"
chrono = { version = "0.4.31", features = ["serde"] }
env_logger = "0.10.1"
mime = "0.3.17"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
